// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebsiteLocalizeRoutesService.Areas.Admin.Controllers
{
    public partial class RouteResourceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RouteResourceController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RouteResourceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Get()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Get);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Save()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Save);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Images()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Images);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RouteResourceController Actions { get { return MVC.Admin.RouteResource; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "RouteResource";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "RouteResource";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Find = "Find";
            public readonly string Get = "Get";
            public readonly string Save = "Save";
            public readonly string Delete = "Delete";
            public readonly string Upload = "Upload";
            public readonly string Images = "Images";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Find = "Find";
            public const string Get = "Get";
            public const string Save = "Save";
            public const string Delete = "Delete";
            public const string Upload = "Upload";
            public const string Images = "Images";
        }


        static readonly ActionParamsClass_Find s_params_Find = new ActionParamsClass_Find();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Find FindParams { get { return s_params_Find; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Find
        {
            public readonly string id = "id";
            public readonly string route = "route";
            public readonly string languageID = "languageID";
            public readonly string saveError = "saveError";
        }
        static readonly ActionParamsClass_Get s_params_Get = new ActionParamsClass_Get();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get GetParams { get { return s_params_Get; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Save s_params_Save = new ActionParamsClass_Save();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Save SaveParams { get { return s_params_Save; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Save
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string deleteID = "deleteID";
            public readonly string pageRoute = "pageRoute";
            public readonly string pageLanguage = "pageLanguage";
        }
        static readonly ActionParamsClass_Upload s_params_Upload = new ActionParamsClass_Upload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Upload UploadParams { get { return s_params_Upload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Upload
        {
            public readonly string file = "file";
            public readonly string ckEditorFuncNum = "ckEditorFuncNum";
            public readonly string ckEditor = "ckEditor";
            public readonly string langCode = "langCode";
        }
        static readonly ActionParamsClass_Images s_params_Images = new ActionParamsClass_Images();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Images ImagesParams { get { return s_params_Images; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Images
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Index_cshtml = "Index.cshtml";
                public readonly string ResourceEditor = "ResourceEditor";
                public readonly string Upload = "Upload";
                public readonly string UploadNew = "UploadNew";
            }
            public readonly string Index = "~/Areas/Admin/Views/RouteResource/Index.cshtml";
            public readonly string Index_cshtml = "~/Areas/Admin/Views/RouteResource/Index.cshtml.pp";
            public readonly string ResourceEditor = "~/Areas/Admin/Views/RouteResource/ResourceEditor.cshtml";
            public readonly string Upload = "~/Areas/Admin/Views/RouteResource/Upload.cshtml";
            public readonly string UploadNew = "~/Areas/Admin/Views/RouteResource/UploadNew.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RouteResourceController : WebsiteLocalizeRoutesService.Areas.Admin.Controllers.RouteResourceController
    {
        public T4MVC_RouteResourceController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void FindOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string route, int languageID, string saveError);

        public override System.Web.Mvc.ActionResult Find(int id, string route, int languageID, string saveError)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Find);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "route", route);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "languageID", languageID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "saveError", saveError);
            FindOverride(callInfo, id, route, languageID, saveError);
            return callInfo;
        }

        partial void GetOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        public override System.Web.Mvc.JsonResult Get(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Get);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetOverride(callInfo, id);
            return callInfo;
        }

        partial void SaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, WebsiteLocalizeRoutesService.Areas.Admin.Models.RouteResourceEditModel model);

        public override System.Web.Mvc.ActionResult Save(WebsiteLocalizeRoutesService.Areas.Admin.Models.RouteResourceEditModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Save);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveOverride(callInfo, model);
            return callInfo;
        }

        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int deleteID, string pageRoute, int pageLanguage);

        public override System.Web.Mvc.ActionResult Delete(int deleteID, string pageRoute, int pageLanguage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deleteID", deleteID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageRoute", pageRoute);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pageLanguage", pageLanguage);
            DeleteOverride(callInfo, deleteID, pageRoute, pageLanguage);
            return callInfo;
        }

        partial void UploadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Upload()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Upload);
            UploadOverride(callInfo);
            return callInfo;
        }

        partial void UploadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase file, string ckEditorFuncNum, string ckEditor, string langCode);

        public override System.Web.Mvc.ActionResult Upload(System.Web.HttpPostedFileBase file, string ckEditorFuncNum, string ckEditor, string langCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckEditorFuncNum", ckEditorFuncNum);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ckEditor", ckEditor);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "langCode", langCode);
            UploadOverride(callInfo, file, ckEditorFuncNum, ckEditor, langCode);
            return callInfo;
        }

        partial void ImagesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        public override System.Web.Mvc.ActionResult Images(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Images);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ImagesOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
